name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  uuid: ^4.5.1
  intl: ^0.19.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  socket_io_client: ^2.0.3+1
  flutter_local_notifications: ^17.2.3
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  barcode: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
